# Generated by Django 5.1.2 on 2024-11-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('anio', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, default='celu_img/default.jpg', null=True, upload_to='celu_img')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
