# Generated by Django 5.1.2 on 2024-10-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
