# Generated by Django 5.1.2 on 2024-11-03 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_celular_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='fecha',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
