# Generated by Django 5.1.2 on 2024-11-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_celular_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celular',
            name='fecha',
        ),
    ]
