# Generated by Django 5.1.2 on 2024-11-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_descripcion_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='descripcion',
            name='desc',
            field=models.CharField(default='Texto.', max_length=130),
        ),
    ]
