# Generated by Django 5.1.2 on 2024-11-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_about_remove_descripcion_descripcion_and_more'),
    ]

