# Generated by Django 5.1.2 on 2024-11-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_delete_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
